extends Node

func data() -> Dictionary:
	return {
		"initial values" : {
			"starting_funds" : 25,
			"starting_rep" : 0,
			"total_artifacts" : 6
		},
		
		"tools" : [
			{
				"id" : 0,
				"name" : "Tool 1",
				"cost" : 300,
				"unlock_required_rep" : 75,
				"is_purchased" : false
			},
					{
				"id" : 1,
				"name" : "Tool 2",
				"cost" : 2000,
				"unlock_required_rep" : 325,
				"is_purchased" : false
			},
		],
		
		"areas" : [
			{
				"id" : 0,
				"name" : "Zone 1",
				"unlock_required_rep" : 0,
				"success_chance" : 0.35,
				"failure_reward" : 5,
				"artifacts" : [
					{
						"id" : 0,
						"area" : 0,
						"name" : "Zone 1 art 1",
						"total_fragments" : 4,
						"attempt_duration" : 10,
						"required_tool" : [],
						"rep_reward" : 10,
						"uncleaned_fragment_funds_ps" : 5,
						"cleaned_fragment_funds_ps" : 15,
						"completed_funds" : 100,
						"success_chance" : 40,
						"failure_reward" : 5,
					},
					{
						"id" : 1,
						"area" : 0,
						"name" : "Zone 1 art 2",
						"total_fragments" : 4,
						"attempt_duration" : 20,
						"required_tool" : [],
						"rep_reward" : 25,
						"uncleaned_fragment_funds_ps" : 20,
						"cleaned_fragment_funds_ps" : 50,
						"completed_funds" : 1000,
						"success_chance" : 25,
						"failure_reward" : 10,
					},
					{
						"id" : 2,
						"area" : 0,
						"name" : "Zone 1 art 3",
						"total_fragments" : 4,
						"attempt_duration" : 40,
						"required_tool" : [0],
						"rep_reward" : 100,
						"uncleaned_fragment_funds_ps" : 50,
						"cleaned_fragment_funds_ps" : 100,
						"completed_funds" : 3000,
						"success_chance" : 10,
						"failure_reward" : 25,
					},
				],
				"speed_upgrade" : {
						"name" : "speed",
						"max_level" : 10,
						"time_dec_per_level" : 2,
						"base_cost" : 30,
						"cost_mult_per_level" : 2,
				},
				"chance_upgrade" : {
						"name" : "chance",
						"max_level" : 10,
						"chance_inc_per_level" : 5,
						"base_cost" : 30,
						"cost_mult_per_level" : 2,
				},
			},
			{
				"id" : 1,
				"name" : "Zone 2",
				"unlock_required_rep" : 35,
				"artifacts" : [
					{
						"id" : 3,
						"area" : 1,
						"name" : "Zone 2 art 1",
						"total_fragments" : 4,
						"attempt_duration" : 20,
						"required_tool" : [],
						"rep_reward" : 40,
						"uncleaned_fragment_funds_ps" : 35,
						"cleaned_fragment_funds_ps" : 70,
						"completed_funds" : 2500,
						"success_chance" : 20,
						"failure_reward" : 25,
					},
					{
						"id" : 4,
						"area" : 1,
						"name" : "Zone 2 art 2",
						"total_fragments" : 4,
						"attempt_duration" : 45,
						"required_tool" : [0],
						"rep_reward" : 150,
						"uncleaned_fragment_funds_ps" :50,
						"cleaned_fragment_funds_ps" : 100,
						"completed_funds" : 5000,
						"success_chance" : 10,
						"failure_reward" : 50,
					},
					{
						"id" : 5,
						"area" : 1,
						"name" : "Zone 2 art 3",
						"total_fragments" : 4,
						"attempt_duration" : 80,
						"required_tool" : [1],
						"rep_reward" : 300,
						"uncleaned_fragment_funds_ps" : 150,
						"cleaned_fragment_funds_ps" : 300,
						"completed_funds" : 10000,
						"success_chance" : 5,
						"failure_reward" : 150,
					},
				],
				"speed_upgrade" : {
						"name" : "speed",
						"max_level" : 10,
						"time_dec_per_level" : 2,
						"base_cost" : 10,
						"cost_mult_per_level" : 2,
					},
				"chance_upgrade" : {
						"name" : "chance",
						"max_level" : 10,
						"chance_inc_per_level" : 5,
						"base_cost" : 10,
						"cost_mult_per_level" : 2,
				},
			},
		]
	}
